name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "Build"
  Build:
    runs-on: [windows-latest]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore GitHubActionMVCDemo.sln

    - name: Build the Solution
      run: msbuild GitHubActionMVCDemo.sln /p:Configuration=Release
      
    - name: Run Test
      run:  '& "$(vswhere -property installationPath)\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" GitHubActionMVCDemo.Tests\bin\Release\GitHubActionMVCDemo.Tests.dll '

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
            name: GitHubActionMVCDemo
            path: "./_build"

